### ISSUE TITLE
Rewrite config_teams_frame()

### ISSUE THREAD

**Issue by reteps** [FRC830/scouting_data_viewer#2]
I rewrote this function so that it's 50% shorter, possibly implement this in the future?

        def config_teams_frame():
            """Set up the frame that shows a list of teams in the current competition."""
            # Initialize Variables
            self.state.teams.sort(key=lambda t: int(t))
            teams_in_row = 10
            left_padding_size = 10

            # Reset Panel
            self.teams_text.config(state=tk.NORMAL)
            self.teams_text.delete('1.0', tk.END)
            self.teams_text.insert(tk.INSERT, '\n')

            # Center-align 'Teams:'
            teams_list_title = 'Teams:\n'
            half_title_len = (len(teams_list_title) - 1) // 2
            title_padding = (left_padding_size + 3 * teams_in_row - half_title_len) * ' '
            self.teams_text.insert(tk.INSERT, title_padding + teams_list_title) 

            num_teams = len(self.state.teams)
            complete_rows = math.floor(num_teams / teams_in_row)
            leftover_teams_count = num_teams % teams_in_row

            # Display teams
            for i in range(complete_rows):
                format_code = left_padding_size * " " + "{: <6}" * teams_in_row + "\n"
                print("starting team:", i * teams_in_row, i * teams_in_row + teams_in_row)
                team_list = self.state.teams[i * teams_in_row:i * teams_in_row + teams_in_row]
        
                self.teams_text.insert(tk.INSERT, format_code.format(*team_list))

            # Deal with leftover teams
            leftover_format_code = left_padding_size * " " + "{: <6}" * leftover_teams_count + "\n"
            leftover_teams = self.state.teams[num_teams - leftover_teams_count:num_teams]
            self.teams_text.insert(tk.INSERT, leftover_format_code.format(*leftover_teams))
            self.teams_text.config(state=tk.DISABLED)

**Comment by robertm39** [comment]
Nah
